chat_history_lines: null      # keep full previous-day chat (no pruning yet)

# Token budgets
per_agent:
  discussion: 50       # multiplied by living agents
  nomination: 50       # multiplied by living agents

defense: 75            # defendant only
judgement:
  total: 150           # global budget
  tail_after_all_votes: 50

last_words:
  defendant: 50
  post_reveal_global: 75

night_channel: 50       # per voice channel 